django/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core import views

urlpatterns = [
    path('deal-gamelle', views.DealGamelle_View.as_view(), name="deal_gamelle"),
]

django/gamelle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/update_client_profile', views.UpdateClientProfile_View.as_view(), name="update_client_profile"),
    path('accounts/', include('allauth.urls')),

    path('core/', include('core.urls')),

    path('', views.Home_View.as_view(), name="home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/core/forms.py
#-*- coding: utf-8 -*-

import copy
import datetime

from allauth.account.forms import SignupForm
from django import forms
from django.contrib import messages
from django.contrib.auth.models import Group, User
from django.core.exceptions import ValidationError
from django.db.models import BooleanField, PositiveSmallIntegerField, Value
# from django.db.models.expressions import Case, When
# from django.db.models.functions import Concat
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField
#from tempus_dominus.widgets import DatePicker
from .models import ClientProfile
from . import exceptions

display_for_user_select = {
	'class': 'selectpicker',
	'data-style': 'btn-light px-2',
	'data-width': '90%',
	'data-live-search': 'true',
	'data-live-search-placeholder': "Taper quelques lettres pour rechercher..."
}
# display_for_user_multiselect = copy.deepcopy(display_for_user_select)
# display_for_user_multiselect.update({
# 	'multiple': True
# })
# datepicker_attrs = { 'append': 'fa fa-calendar', 'size': 'large' }

#--------------------------------------------------------------------
class ClientProfile_Mixin(forms.Form):

	class Meta:
		abstract = True

	first_name = forms.CharField(
		max_length=50, label='Prénom', widget=forms.TextInput({
			'class': 'form-control form-control-lg',
			'placeholder': 'Votre prénom'
		}))
	last_name = forms.CharField(
		max_length=50, label='Nom de famille', widget=forms.TextInput({
			'class': 'form-control form-control-lg',
			'placeholder': 'Votre nom'
		}))
	email = forms.EmailField(
		widget=forms.EmailInput({
			'class': 'form-control form-control-lg',
			'placeholder': 'Votre adresse mail',
		}))
	phone_number = PhoneNumberField(
		widget=forms.TextInput({
			'class': 'form-control form-control-lg',
			'placeholder': 'Votre numéro de téléphone'
		}))
	
	def clean_first_name(self):
		return self.cleaned_data["first_name"].title()

	def clean_last_name(self):
		return self.cleaned_data["last_name"].upper()

	# def clean_phone_number(self):
	# 	"""
	# 	TODO : peut-être rien à faire avec le module phonenumber, à tester en pratique
	# 	"""
	# 	return self.cleaned_data["phone_number"]

class CustomSignup_Form(ClientProfile_Mixin, SignupForm):

	# NOTE : à changer
	# pas de username à renseigner à l'inscription, 
	# celui-ci est défini automatiquement sur la base prénom.nom

	def save(self, request):
		try:
			#------------------------------------------------------------------
			# par défaut
			user = super(CustomSignup_Form, self).save(request)
			#------------------------------------------------------------------
			# on met à jour les attributs de user
			user.first_name = self.cleaned_data['first_name']
			user.last_name = self.cleaned_data['last_name']
			#user.username = self.cleaned_data['first_name'].lower() + '.' + self.cleaned_data['last_name'].lower()
			# on associe le groupe RegularAccount par défaut
			#user.groups.add(Group.objects.get(name='RegularAccount'))
			user.save()
			#------------------------------------------------------------------
			# on créé le profil utilisateur associé
			new_profile = ClientProfile(user=user, phone_number=self.cleaned_data["phone_number"])
			new_profile.save()
			print("TEL VAUT : ", new_profile.phone_number)
			#------------------------------------------------------------------
			user.save()
			return user
		
		except Exception as e:
			print("Problème dans l'inscription d'un utilisateur (CustomSignup_Form) : ", e)
			try:
				u = User.objects.get(username=self.cleaned_data.get('username'))
				u.delete()
			except User.DoesNotExist: 
				print("Aucun utilisateur avec le username {}.".format(self.cleaned_data.get('username')))
			except Exception as e:
				raise e # message d'erreur personnalisé à réaliser

class UpdateClientProfile_Form(ClientProfile_Mixin):

	def __init__(self, user, *args, **kwargs):
		self.user = user
		super().__init__(*args, **kwargs)

	def clean_email(self):
		""" On vérifie qu'on ne choisit pas le même email qu'un autre user. """
		new_email = self.cleaned_data['email']
		try:
			if self.user == User.objects.get(email=new_email):
				return new_email			
			else:
				raise forms.ValidationError(
					_("Cet email est déjà utilisé par un autre utilisateur."),
					code='email_already_taken'
				)
		except User.DoesNotExist:
			return new_email

	def clean(self):
		cleaned_data = super(UpdateClientProfile_Form, self).clean()
		return cleaned_data

	def save(self):
		UserToUpdate = User.objects.get(username=self.user.username)
		ClientProfileToUpdate = UserToUpdate.client_profile
		#-----------------------
		UserToUpdate.username = self.cleaned_data['first_name'].lower() + '.' + self.cleaned_data['last_name'].lower()
		UserToUpdate.first_name = self.cleaned_data['first_name']
		UserToUpdate.last_name = self.cleaned_data['last_name']
		UserToUpdate.email = self.cleaned_data['email']
		#-----------------------
		ClientProfileToUpdate.team = self.cleaned_data['team']
		#-----------------------
		UserToUpdate.save()
		ClientProfileToUpdate.save()


class DealWithGamelle_Form(forms.Form):
	""" Formulaire permettant d'utiliser, rendre ou échanger une gamelle """

	action = forms.CharField(max_length=10)

	restaurant_to_select = forms.ModelChoiceField(
		queryset=User.objects.filter(restaurant_profile__isnull=False),
		widget=forms.Select({
            'class': 'selectpicker',
            'data-style': 'btn-light px-2 mx-auto',
            'data-width': '100%',
            'data-live-search': 'true',
            'data-live-search-placeholder': "Taper quelques lettres pour rechercher..."
        })
	)

	# code_to_submit = forms.CharField(
	# 	max_length=15, label='Code restaurateur', 
	# 	widget=forms.TextInput({
	# 		'class': 'form-control form-control-lg',
	# 		'placeholder': 'Code restaurateur'
	# 	}))
	
	nbr_gamelles = forms.IntegerField(min_value=0, max_value=1000, initial=0)

	def __init__(self, *args, **kwargs):
		# NOTE : le pop doit bien avoir lieu avant d'appeler super,
		# car la méthode super ne reconnaîtrait pas user comme kwargs sinon
		self.user = kwargs.pop('user', None)
		if not self.user:
			raise exceptions.DontKnowWhoFillsForm_Error()
		super(DealWithGamelle_Form, self).__init__(*args, **kwargs)

	def clean(self):
		cleaned_data = super(DealWithGamelle_Form, self).clean()
		ValidationErrorList = []
		#code_to_submit = cleaned_data.get("code_to_submit")
		restaurant_to_select = cleaned_data.get("restaurant_to_select")

		# if not restaurant_to_select.restaurant_profile.is_code_submitted_correct(code_to_submit):
		# 	ValidationErrorList.append(ValidationError(
		# 		_("Le code restaurateur ne correspond pas."),
		# 		code="restaurant_code_does_not_match"
		# 	))

		if ValidationErrorList != []:
			raise ValidationError(ValidationErrorList)

		return cleaned_data

django/core/views.py
from django.contrib import messages
from django.contrib.auth.mixins import (AccessMixin, LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, FormView,
                                  ListView, RedirectView, TemplateView,
                                  UpdateView)

from . import exceptions
from . import forms as gamelle_forms
from . import messages as gamelle_messages
from django.conf import settings

class Home_View(TemplateView):
	template_name = 'core/home.html'


# --------------------------------------------------------------
class UpdateClientProfile_View(LoginRequiredMixin, FormView):
	"""
	Vue qui permet de mettre à jour le profil utilisateur.
	Seul le mot de passe n'est pas mis à jour par l'intermédiaire de cette vue :
	on utilise plutôt la vue fournie avec django-allauth.
	"""
	form_class = gamelle_forms.UpdateClientProfile_Form
	template_name = 'account/update_client_profile.html'
	success_url = reverse_lazy("update_client_profile")
	success_message = gamelle_messages.SUCCESS_UPDATE_USER_PROFILE

	def form_valid(self, form):
		try:
			form.save()
			messages.success(self.request, self.success_message, extra_tags='safe')
			return super().form_valid(form)
		except Exception as e:
			print("Erreur inattendue dans UpdateClientProfile_View : ", e)
			messages.error(self.request, nounou_messages.ERROR_M_UNEXPECTED, extra_tags='safe')

	def get_form_kwargs(self):
		""" Return the keyword arguments for instantiating the form. """
		kwargs = super().get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

	def get_initial(self):
		initial = {
			'username': self.request.user.username,
			'first_name': self.request.user.first_name,
			'last_name': self.request.user.last_name,
			'email': self.request.user.email, 
			'phone_number': self.request.user.client_profile.phone_number
		}
		return initial

class DealGamelle_View(LoginRequiredMixin, FormView):
	template_name = 'core/deal_gamelle.html'
	success_url = reverse_lazy('home')
	form_class = gamelle_forms.DealWithGamelle_Form
	success_message = {
		'use': gamelle_messages.SUCCESS_USE_GAMELLE,
		'give_back': gamelle_messages.SUCCESS_GIVE_BACK_GAMELLE,
		'swap': gamelle_messages.SUCCESS_SWAP_GAMELLE
	}

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		if hasattr(self, 'object'):
			kwargs.update({'instance': self.object})
		kwargs.update({'user': self.request.user})
		return kwargs

	def form_valid(self, form):
		# messages.success(self.request, self.success_message, extra_tags='safe')
		# print(form.cleaned_data)
		try:
			nbr_gamelles = form.cleaned_data['nbr_gamelles']
			client_profile = self.request.user.client_profile
			restaurant_profile = form.cleaned_data['restaurant_to_select'].restaurant_profile

			if form.cleaned_data['action'] == 'use':
				amount_to_debit = nbr_gamelles * settings.GAMELLE_VALUE
				client_profile.debit(amount_to_debit)
				client_profile.borrow_gamelle(nbr_gamelles)
				restaurant_profile.give_gamelle(nbr_gamelles)
				client_profile.save()
				restaurant_profile.save()

			elif form.cleaned_data['action'] == 'give_back':
				amount_to_credit = nbr_gamelles * settings.GAMELLE_VALUE
				client_profile.credit(amount_to_credit)
				client_profile.bring_back_gamelle(nbr_gamelles)
				restaurant_profile.bring_back_gamelle(nbr_gamelles)
				client_profile.save()
				restaurant_profile.save()

			elif form.cleaned_data['action'] == 'swap':
				# TODO:  à venir
				pass

			else:
				# TODO : raise une exception ici
				pass

			messages.success(
				self.request, 
				self.success_message[form.cleaned_data['action']], 
				extra_tags='safe')
			return super().form_valid(form)
		
		except (
			exceptions.CantDebitIfNotEnoughBalance_Error, 
			exceptions.CantBringBackGamelleYouDontHave_Error,
			exceptions.NotEnoughGamellesToGive_Error) as e:
			messages.error(self.request, e.msg_for_user, extra_tags='safe')
		
		except Exception as e:
			print("Erreur inattendue dans DealGamelle_View : ", e)
			messages.error(self.request, gamelle_messages.ERROR_M_UNEXPECTED, extra_tags='safe')
		
		return redirect(self.request.META['HTTP_REFERER'])
		
		
			


	# def get_context_data(self, **kwargs):
	# 	context = super().get_context_data(**kwargs)
	# 	context['DealWithGamelle_Form'] = gamelle_forms.DealWithGamelle_Form
	# 	return context

# --------------------------------------------------------------
class BorrowGamelle_View(LoginRequiredMixin, RedirectView):
	pass

django/core/templates/core/deal_gamelle.html
{% extends "base.html" %}
{% load static %}{% load templateTags %}{% load i18n %}

{% block addCSS %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="{% static 'core/deal_gamelle.css' %}">
{% endblock addCSS %}

{% block addJS %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
    <script>
    $( document ).ready(function() {

        // initialisation
        $("#nbr-gamelles-is").html($("#id_nbr_gamelles").val())
        $("#id_action").val('use')
        $("#amount-is").html($("#id_nbr_gamelles").val() * {{ GAMELLE_VALUE }})

        $(".action-input").change(function() {
            var btn_group = $('#action-gamelle-btns')
            btn_group.children().removeClass('btn-success btn-warning btn-purple btn-danger').addClass('btn-light-blue')
            $(this).parent().removeClass('btn-light-blue').addClass('btn-success')
            if ($(this).attr('data-action') == 'use') { 
                $("#id_action").val('use')
                $("#action-is").html('utilisez') 
                $("#resume-cagnotte").show()
                $("#cagnotte-is").html('débitée').addClass('text-danger').removeClass('text-success')
            } else if ($(this).attr('data-action') == 'give_back') { 
                $("#id_action").val('give_back')
                $("#action-is").html('rendez') 
                $("#resume-cagnotte").show()
                $("#cagnotte-is").html('créditée').addClass('text-success').removeClass('text-danger')
            } else if ($(this).attr('data-action') == 'swap') { 
                $("#id_action").val('swap')
                $("#action-is").html('échangez')
                $("#resume-cagnotte").hide()
            }
        })
        $(".minus, .plus").click(function() {
            console.log("{{ user.client_profile.current_balance }}€")
            console.log($("#id_nbr_gamelles").val())
            $("#nbr-gamelles-is").html($("#id_nbr_gamelles").val())
            $("#amount-is").html($("#id_nbr_gamelles").val() * {{ GAMELLE_VALUE }})
        })
    })
    </script>
{% endblock addJS %}

{% block title %}Les gamelles{% endblock title %}

{% block content %}

<div class="container mt-3">
    {% include "display_alerts.html" %}
</div>

<form class="container mt-3 mb-4 text-center" method="post" action="{% url 'deal_gamelle' %}">

    {% csrf_token %}

    {% if form.error %}
    <div class="container-fluid">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {% trans "Merci de corriger les erreurs ci-dessous" %}
        </div>
    </div>
    {% endif %}
    
    {% if form.non_field_errors %}
        {% include "display_single_alert.html" with field_=form.non_field_errors %}
    {% endif %}

    <div id="action-gamelle-btns" class="btn-group col-12 px-2" data-toggle="buttons">
        {{ form.action.as_hidden }}
        <label class="btn btn-success px-3 form-check-label active">
            <input class="form-check-input action-input" type="radio" autocomplete="off" checked hidden
            data-action='use'>
            Utiliser
        </label>
        <label class="btn btn-light-blue px-3 form-check-label">
            <input class="form-check-input action-input" type="radio" autocomplete="off" hidden
            data-action='give_back'>
            Rendre
        </label>
        <label class="btn btn-light-blue px-3 form-check-label">
            <input class="form-check-input action-input" type="radio" autocomplete="off" hidden
            data-action='swap'>
            Echanger
        </label>
    </div>

    <div class="col-12 d-flex justify-content-center mt-3">
        <i class="fas fa-archive fa-3x mr-3"></i>
        {% include "plus_minus_button.html" with field=form.nbr_gamelles %}
    </div>

    <div class="col-12 mt-3 pt-2 border-top border-light">
        {{ form.restaurant_to_select }}
    </div>

    {% comment %} <div class="col-12 mt-3">
        {{ form.code_to_submit }}
    </div> {% endcomment %}

    <div class="col-12 mt-3 pt-3 border-top border-light">
        <strong>Résumé</strong>
        <ul class="text-left pl-2">
            <li>Vous <span id="action-is">utilisez</span> <span id="nbr-gamelles-is">0</span> gamelle(s)</li>
            <li id="resume-cagnotte">Votre cagnotte est <strong id="cagnotte-is" class="text-danger">débitée</strong> de <span id="amount-is">0</span>€</li>
        </ul>
    </div>
    
    <div class="col-12 mt-3 border-top border-light">
        <button class="btn btn-block btn-success" type="submit">
            Valider
        </button>
    </div>

</form>

{% endblock content %}

django/core/templates/core/home.html
{% extends "base.html" %}
{% load static %}{% load templateTags %}

{% block addCSS %}
<link rel="stylesheet" href="{% static 'core/home.css' %}">
{% endblock addCSS %}

{% block title %}Accueil{% endblock title %}

{% block content %}

<div class="container mt-3">
    {% include "display_alerts.html" %}
</div>

<div class="container mt-3 text-center">

    <img src="{% static 'images/logo/logo_la_gamelle_consignee.png' %}" 
    class="img-fluid mx-auto" alt="logo_la_gamelle_consignee" width="200">

    {% if user.is_authenticated %}
        <div class="container d-flex justify-content-center flex-column">
            <div class="row mt-2">
                <a href="" role="button" class="btn btn-info btn-block mx-auto px-2">
                    Voir la liste des restaurants qui utilisent la consigne
                </a>
            </div>
            <div class="row mt-2">
                <a href="{% url 'deal_gamelle' %}" role="button" class="btn btn-secondary btn-block mx-auto px-2">
                    Utiliser, rendre ou échanger une gamelle
                </a>
            </div>

            {% comment %}
            <div class="row mt-2">
                <a href="" role="button" class="btn btn-warning btn-block mx-auto px-2">
                    Utiliser ma cagnotte (xx€)
                    <br>Rendre mes consignes
                </a>
            </div>
            <div class="row mt-2">
                <a href="" role="button" class="btn btn-secondary btn-block mx-auto px-2">
                    Alimenter ma cagnotte<br>
                    Se faire rembourser
                </a>
            </div>
            {% endcomment %}
        </div>
    {% else %}

    <div class="row mt-2">
        <div class="col-12">
            <hr>
            <h2 class="h2-responsive">Vous n'êtes pas connecté(e)</h2> 
            <hr>           
        </div>
        <div class="col-12 col-md-6">
            <a role="button" href="{% url 'account_signup' %}" class="w-100 btn btn-lg btn-success">
                Créer un compte
            </a>
        </div>
        <div class="col-12 col-md-6">
            <a role="button" href="{% url 'account_login' %}" class="w-100 btn btn-lg btn-info">
                Se connecter
            </a>
        </div>
    </div>

    {% endif %}

</div>

{% endblock content %}